export const INPUT_CHANGE = 'INPUT_CHANGE';
export const GET_ENCODE_DECODE_REQUEST = 'GET_ENCODE_DECODE_REQUEST';
export const GET_ENCODE_SUCCESS = 'GET_ENCODE_SUCCESS';
export const GET_DECODE_SUCCESS = 'GET_DECODE_SUCCESS';
export const GET_ENCODE_DECODE_FAILURE = 'GET_ENCODE_DECODE_FAILURE';
export const GET_INFORMED = 'GET_INFORMED';