export const INPUT_CHANGE = 'INPUT_CHANGE';
export const GET_ENCODE_REQUEST = 'GET_ENCODE_REQUEST';
export const GET_ENCODE_SUCCESS = 'GET_ENCODE_SUCCESS';
export const GET_ENCODE_FAILURE = 'GET_ENCODE_FAILURE';